---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-busybox
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nfs-busybox
  template:
    metadata:
      labels:
        name: nfs-busybox
    spec:
      containers:
        - image: busybox
          command:
            - sh
            - -c
            - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
          imagePullPolicy: IfNotPresent
          name: busybox
          volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/mnt"
      volumes:
        - name: nfs
          nfs:
            server: 10.2.1.2
            path: "/mnt/pool_01/Downloads"
