---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1l3wp6gygpfnqyttggpqyy7460jqryvfnlxsr97tyqvtmadc4kq9q28dy8y
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1l3wp6gygpfnqyttggpqyy7460jqryvfnlxsr97tyqvtmadc4kq9q28dy8y
