---
kubernetes:
  children:
    master:
      hosts:
        sb1:
          ansible_host: 10.3.100.101
        sb2:
          ansible_host: 10.3.100.102
        sb3:
          ansible_host: 10.3.100.103
