---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/London
  METALLB_LB_RANGE: 10.3.100.150-10.3.100.200
  METALLB_K8S_GATEWAY_ADDR: 10.3.100.150
  METALLB_TRAEFIK_ADDR: 10.3.100.151
