kind: Secret
ansible_user: ENC[AES256_GCM,data:el2uI+k=,iv:61H1ZP6qctPx1tJ2CVDEDEFDyhg9GJ+lZjyg9OPB0SU=,tag:0otySAPGw+HHBMAtnLGqEA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WtzGSCKDjUweocSc,iv:4gO8x/Ab0uKDK2JU8QB8Ze2NaHkVSf6IksI19CCCKBg=,tag:Xm5xdPW3Z2uetyTubJDlVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l3wp6gygpfnqyttggpqyy7460jqryvfnlxsr97tyqvtmadc4kq9q28dy8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTUliTWRMRGtGZEo1L3Zi
            WmhjRHdpSTIyK1kwQThXcjEvRVV1SXhab25JClJ4emcrNk1tcEZNcEFYL3gwWnBC
            cjlWR3plckNtYmN1RDNzdW9oblUrdm8KLS0tIDlpMWlIUUhUajQ0eW0yNW9jWm0r
            S3FVb3VFOEoxY1ZLRUg1Q3B2bVo2L1UK523yldfBwcUJM4K63iYlkZXUU/oTmKNe
            bU9WHlY+BsWZXZoANzVpNxOue5DSxEiivFkWa3uHW0nSsTPSXIE0EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-28T22:08:44Z"
    mac: ENC[AES256_GCM,data:5sy6a49M0EQitvd3U4ResmLXlfXJjdPgTMzOQ7cJH2dm/Pv/FZ3tLJKpTnxmr96vLTA3ksC5ra1TFgdmHuTXBj/CPbns1Gb/PgTMDeQCUsRfWEPxi6TRsN0FQbqL/g5mgoqKEosbPi+PX2exsoIgzSx4NaZFdFoHRhpssb8DE4g=,iv:Do07BvycQGpWDVXHZ0Q8CcV4TtKuvx1+UbKu/KzoIkk=,tag:O2shDqFohzsOSYI6wB7a8g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
